# Generated by Django 6.1.1 on 2026-10-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn', models.CharField(max_length=12, unique=True)),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NON_FICTION', 'Non-Fiction'), ('FANTASY', 'Fantasy'), ('SCIENCE', 'Science'), ('BIOGRAPHY', 'Biography'), ('CRIME', 'Crime'), ('MYSTERY', 'Mystery'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('HISTORY', 'History'), ('HORROR', 'Horror')], max_length=100)),
                ('publishing_date', models.DateField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
